### ISSUE TITLE
SDL_GL_CreateContext(window); return NULL

### ISSUE THREAD

**Issue by Match-Yang** [mortennobel/SimpleRenderEngineProject#4]
I'm using ubuntu14.04 
g++ version is 6.04.0
SDL2 version is 2.0.2(install via apt-get install)
glGetString(GL_VERSION) return NULL too.

When  I run the examples,just crash.please help...

**Comment by mortennobel** [comment]
What OpenGL version is supported by your driver?

See this using:

    sudo apt install mesa-utils
    glxinfo | grep "OpenGL version"

(From https://askubuntu.com/questions/47062/what-is-terminal-command-that-can-show-opengl-version )

**Comment by mortennobel** [comment]
The develop branch of SimpleRenderEngine will now give an error message (instead of a crash) if OpenGL is not supported.

**Comment by Match-Yang** [comment]
OpenGL version string: 4.5.0 NVIDIA 384.130
